const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const roles = [
    {
      name: 'ADMIN',
      description: 'Admin role with Full permissions',
      permissions: {
        approver: true,
        createProduct: true,
        updateProduct: true,
        deleteProduct: true,
        viewProduct: true,
        createCategory: true,
        updateCategory: true,
        deleteCategory: true,
        viewCategory: true,
        createSupplier: true,
        updateSupplier: true,
        deleteSupplier: true,
        viewSupplier: true,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: true,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: true,
        viewInvoice: true,
        cancelRequest: true,
        stockTransfer: true,
        createTransaction: true,
        viewTransaction: true,
        createUser: true,
        updateUser: true,
        deleteUser: true,
        viewUser: true,
        createRole: true,
        updateRole: true,
        deleteRole: true,
        viewRole: true,
        createPurchaseOrder: true,
        updatePurchaseOrder: true,
        deletePurchaseOrder: true,
        viewPurchaseOrder: true,
        createSalesOrder: true,
        updateSalesOrder: true,
        deleteSalesOrder: true,
        viewSalesOrder: true,
        createPayment: true,
        updatePayment: true,
        deletePayment: true,
        viewPayment: true,
        createRequest: true,
        updateRequest: true,
        deleteRequest: true,
        viewRequest: true,
        cancelOrder: true,
        purchaseOderConfirmation: true,
        adjustStock: true,
        viewReport: true,
        createWarehouse: true,
        updateWarehouse: true,
        deleteWarehouse: true,
      },
    },
    {
      name: 'INTERN',
      description: 'Intern role with limited permissions',
      permissions: {
        approver: false,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: true,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: false,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: false,
        viewCustomer: true,
        createInvoice: false,
        updateInvoice: false,
        deleteInvoice: false,
        viewInvoice: true,
        cancelRequest: false,
        stockTransfer: false,
        createTransaction: false,
        viewTransaction: false,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: false,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: false,
        createPurchaseOrder: false,
        updatePurchaseOrder: false,
        deletePurchaseOrder: false,
        viewPurchaseOrder: false,
        createSalesOrder: false,
        updateSalesOrder: false,
        deleteSalesOrder: false,
        viewSalesOrder: false,
        createPayment: false,
        updatePayment: false,
        deletePayment: false,
        viewPayment: false,
        createRequest: true,
        updateRequest: true,
        deleteRequest: false,
        viewRequest: true,
        cancelOrder: false,
        purchaseOderConfirmation: false,
        adjustStock: false,
        viewReport: false,
        createWarehouse: false,
        updateWarehouse: false,
        deleteWarehouse: false,
      },
    },
    {
      name: 'SALESREP',
      description: 'SalesRep role with limited permissions',
      permissions: {
        approver: false,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: true,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: false,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: false,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        cancelRequest: true,
        stockTransfer: true,
        createTransaction: false,
        viewTransaction: false,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: false,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: false,
        createPurchaseOrder: false,
        updatePurchaseOrder: false,
        deletePurchaseOrder: false,
        viewPurchaseOrder: false,
        createSalesOrder: false,
        updateSalesOrder: false,
        deleteSalesOrder: false,
        viewSalesOrder: false,
        createPayment: false,
        updatePayment: false,
        deletePayment: false,
        viewPayment: false,
        createRequest: true,
        updateRequest: true,
        deleteRequest: false,
        viewRequest: true,
        cancelOrder: false,
        purchaseOderConfirmation: false,
        adjustStock: true,
        viewReport: true,
        createWarehouse: true,
        updateWarehouse: true,
        deleteWarehouse: false,
      },
    },
    {
      name: 'CASHIER',
      description: 'Cashier role with limited permissions',
      permissions: {
        approver: false,
        createProduct: false,
        updateProduct: true,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: true,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: false,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: false,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        cancelRequest: false,
        stockTransfer: false,
        createTransaction: true,
        viewTransaction: true,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: false,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: false,
        createPurchaseOrder: true,
        updatePurchaseOrder: true,
        deletePurchaseOrder: false,
        viewPurchaseOrder: true,
        createSalesOrder: true,
        updateSalesOrder: true,
        deleteSalesOrder: false,
        viewSalesOrder: true,
        createPayment: true,
        updatePayment: true,
        deletePayment: false,
        viewPayment: true,
        createRequest: true,
        updateRequest: true,
        deleteRequest: false,
        viewRequest: true,
        cancelOrder: true,
        purchaseOderConfirmation: false,
        adjustStock: true,
        viewReport: true,
        createWarehouse: false,
        updateWarehouse: false,
        deleteWarehouse: false,
      },
    },
    {
      name: 'SUPERVISOR',
      description: 'Supervisor role with limited permissions',
      permissions: {
        approver: true,
        createProduct: true,
        updateProduct: true,
        deleteProduct: false,
        viewProduct: true,
        createCategory: true,
        updateCategory: true,
        deleteCategory: false,
        viewCategory: true,
        createSupplier: true,
        updateSupplier: true,
        deleteSupplier: false,
        viewSupplier: true,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: false,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        cancelRequest: true,
        stockTransfer: true,
        createTransaction: true,
        viewTransaction: true,
        createUser: true,
        updateUser: true,
        deleteUser: false,
        viewUser: true,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: true,
        createPurchaseOrder: true,
        updatePurchaseOrder: true,
        deletePurchaseOrder: false,
        viewPurchaseOrder: true,
        createSalesOrder: true,
        updateSalesOrder: true,
        deleteSalesOrder: true,
        viewSalesOrder: true,
        createPayment: true,
        updatePayment: true,
        deletePayment: false,
        viewPayment: true,
        createRequest: true,
        updateRequest: true,
        deleteRequest: false,
        viewRequest: true,
        cancelOrder: true,
        purchaseOderConfirmation: true,
        adjustStock: true,
        viewReport: true,
        createWarehouse: true,
        updateWarehouse: true,
        deleteWarehouse: true,
      },
    },
    {
      name: 'EMPLOYEE',
      description: 'Employee role with limited permissions',
      permissions: {
        approver: false,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        viewProduct: true,
        createCategory: false,
        updateCategory: false,
        deleteCategory: false,
        viewCategory: true,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        viewSupplier: false,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: false,
        viewCustomer: true,
        createInvoice: true,
        updateInvoice: true,
        deleteInvoice: false,
        viewInvoice: true,
        cancelRequest: false,
        stockTransfer: false,
        createTransaction: false,
        viewTransaction: false,
        createUser: false,
        updateUser: false,
        deleteUser: false,
        viewUser: false,
        createRole: false,
        updateRole: false,
        deleteRole: false,
        viewRole: false,
        createPurchaseOrder: false,
        updatePurchaseOrder: false,
        deletePurchaseOrder: false,
        viewPurchaseOrder: false,
        createSalesOrder: false,
        updateSalesOrder: false,
        deleteSalesOrder: false,
        viewSalesOrder: false,
        createPayment: false,
        updatePayment: false,
        deletePayment: false,
        viewPayment: false,
        createRequest: true,
        updateRequest: true,
        deleteRequest: false,
        viewRequest: true,
        cancelOrder: false,
        purchaseOderConfirmation: false,
        adjustStock: false,
        viewReport: false,
        createWarehouse: false,
        updateWarehouse: false,
        deleteWarehouse: false,
      },
    },
  ];

  for (const role of roles) {
    await prisma.systemRole.upsert({
      where: { name: role.name },
      update: {
        description: role.description,
        permissions: role.permissions,
      },
      create: {
        name: role.name,
        description: role.description,
        permissions: role.permissions,
      },
    });
  }

  console.log('Successfully seeded');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
